import { createI18n } from 'vue-i18n'

const messages = {
  en: {
    menu: { dashboard: 'Dashboard', sensors: 'Sensors', pcap: 'Traffic Records', rules: 'IDS Rules', rule_sources: 'Rule Sources', vpn: 'VPN Management' },
    header: { title: 'SIEM & SOAR Master Console', lang: 'RU', theme_light: 'Light Theme', theme_dark: 'Dark Theme' },
    common: { add: 'Add', delete: 'Delete Selected', save: 'Save', cancel: 'Cancel', confirm_title: 'Confirm Action', confirm_text: 'Are you sure you want to delete?', confirm_yes: 'Yes, delete', confirm_no: 'Cancel', loading: 'Loading...', success: 'Success', error: 'Error', actions: 'Actions', edit: 'Edit', close: 'Close', status: 'Status', download: 'Download' },
    sensors: { title: 'Sensors Database', name: 'Name', ip: 'IP Address', network: 'Protected Network', desc: 'Description', add_new: 'Register New Sensor', edit_sensor: 'Edit Sensor' },
    rules: { title: 'Suricata Rules Management', select_sensor: 'Select Sensor', no_sensor: 'Please select a sensor to view rules', existing_rules: 'Active Custom Rules', new_rule: 'Add Rule(s)', placeholder: 'alert tcp any any -> any any (msg:"Test"; sid:1000; rev:1;)\nOne rule per line for batch add', deploy: 'Deploy Rule', empty: 'No custom rules found.', deploying: 'Deploying rules to sensor...', deployed: 'Rules deployed successfully!', deploy_error: 'Error deploying rules', batch_progress: 'Adding rules... {current} of {total}', select_source: 'Select Rule Source', update_from_source: 'Update Rules', syncing: 'Synchronizing rules from source...' },
    pcap: { title: 'Traffic Records (PCAP)', desc: 'Select a sensor to view and download traffic records.', refresh: 'Refresh', filename: 'Filename', size: 'Size', date: 'Date', download_btn: 'Download Selected', empty: 'No records found.' },
    dashboard: { ml_status: 'ML Agent Status', start_agent: 'Start Agent', stop_agent: 'Stop Agent', status_active: 'Active', status_inactive: 'Inactive', recent_alerts: 'Recent Anomaly Alerts', empty_active: 'ML Engine is analyzing network traffic...', empty_inactive: 'ML Engine is stopped. Start the agent to detect anomalies.', severity: 'Severity', score: 'Score', kibana: 'Investigate in Kibana', sensor: 'Sensor', algorithm: 'Algorithm', src_ip: 'Source IP' },
    vpn: { title: 'VPN Certificate Management', name: 'Profile Name', status: 'Status', serial: 'Serial Number', create: 'Create Profile', revoke: 'Revoke', empty: 'No certificates found.', creating: 'Generating certificate...', revoking: 'Revoking profile...', status_valid: 'Valid', status_revoked: 'Revoked', confirm_revoke: 'Are you sure you want to revoke the selected profiles?', err_download: 'Error downloading profile', err_revoke: 'Error revoking profiles', err_create: 'Error creating profile' },
    rule_sources: { title: 'Signature Rule Sources', name: 'Name', url: 'Git Repository URL', branch: 'Branch', path: 'Rules File Path', desc: 'Description', add_new: 'Register New Rule Source', edit_source: 'Edit Rule Source', empty: 'No rule sources found.' }
  },
  ru: {
    menu: { dashboard: 'Главная панель', sensors: 'Сенсоры', pcap: 'Записи трафика', rules: 'Правила IDS', rule_sources: 'Источники правил', vpn: 'Управление VPN' },
    header: { title: 'Консоль управления SIEM & SOAR', lang: 'EN', theme_light: 'Светлая тема', theme_dark: 'Темная тема' },
    common: { add: 'Добавить', delete: 'Удалить выбранные', save: 'Сохранить', cancel: 'Отмена', confirm_title: 'Подтверждение', confirm_text: 'Вы уверены в удалении?', confirm_yes: 'Да, удалить', confirm_no: 'Отмена', loading: 'Загрузка...', success: 'Успешно', error: 'Ошибка', actions: 'Действия', edit: 'Редактировать', close: 'Закрыть', status: 'Статус', download: 'Скачать' },
    sensors: { title: 'База сенсоров', name: 'Имя', ip: 'IP Адрес', network: 'Защищаемая сеть', desc: 'Описание', add_new: 'Регистрация сенсора', edit_sensor: 'Изменение сенсора' },
    rules: { title: 'Управление правилами Suricata', select_sensor: 'Выберите сенсор', no_sensor: 'Пожалуйста, выберите сенсор для просмотра правил', existing_rules: 'Пользовательские правила', new_rule: 'Добавить правило/правила', placeholder: 'alert tcp any any -> any any (msg:"Test"; sid:1000; rev:1;)\nПо одному правилу на строку для пакетного добавления', deploy: 'Применить правило', empty: 'Правила не найдены.', deploying: 'Загрузка правил на сенсор...', deployed: 'Правила успешно загружены!', deploy_error: 'Ошибка загрузки правил', batch_progress: 'Добавление правил... {current} из {total}', select_source: 'Выберите источник правил', update_from_source: 'Обновить правила', syncing: 'Синхронизация правил из источника...' },
    pcap: { title: 'Записи трафика (PCAP)', desc: 'Выберите сенсор для просмотра и загрузки записей трафика.', refresh: 'Обновить', filename: 'Имя файла', size: 'Размер', date: 'Дата', download_btn: 'Скачать выбранные', empty: 'Записи не найдены.' },
    dashboard: { ml_status: 'Статус ML-агента', start_agent: 'Запустить агента', stop_agent: 'Остановить агента', status_active: 'Активен', status_inactive: 'Неактивен', recent_alerts: 'Последние алерты аномалий', empty_active: 'Модуль ML-обнаружения запущен. Идет анализ трафика...', empty_inactive: 'Модуль остановлен. Запустите агента для обнаружения.', severity: 'Критичность', score: 'Оценка', kibana: 'Расследовать в Kibana', sensor: 'Сенсор', algorithm: 'Алгоритм', src_ip: 'IP Источника' },
    vpn: { title: 'Управление сертификатами VPN', name: 'Имя профиля', status: 'Статус', serial: 'Серийный номер', create: 'Создать профиль', revoke: 'Отозвать', empty: 'Сертификаты не найдены.', creating: 'Генерация сертификата...', revoking: 'Отзыв профиля...', status_valid: 'Действителен', status_revoked: 'Отозван', confirm_revoke: 'Вы уверены, что хотите отозвать выбранные профили?', err_download: 'Ошибка скачивания профиля', err_revoke: 'Ошибка отзыва профилей', err_create: 'Ошибка создания профиля' },
    rule_sources: { title: 'Источники правил сигнатур', name: 'Название', url: 'URL Git-репозитория', branch: 'Ветка', path: 'Путь к файлу правил', desc: 'Описание', add_new: 'Добавить источник правил', edit_source: 'Изменение источника', empty: 'Источники правил не найдены.' }
  }
}
export const i18n = createI18n({ locale: 'ru', fallbackLocale: 'en', messages })
